- name: First Playbook
  hosts: localhost # or wecan also use from inventory file (local-groupname) and connection: local
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'Hello, Ansible!'
